###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty
$terminalOptions =
$launchInTerminal = alacritty -e

$fileManager = dolphin
$fileManagerOptions = 

$browser = zen-browser
$browserOptions =

$task = $launchInTerminal taskwarrior-tui
$messenger = Telegram


