# Use C-space as the prefix
set -g prefix C-space
bind C-space send-prefix
unbind C-b

# y and p as in vim
unbind p
bind p paste-buffer
bind -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send -X copy-selection
bind -T copy-mode-vi 'Bspace' send -X halfpage-up

# easy-to-remember split pane commands
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# open new windows in the same directory as the current pane
bind c new-window -c "#{pane_current_path}"

# moving between panes with vim movement keys
bind -r C-h select-pane -L
bind -r C-j select-pane -D
bind -r C-k select-pane -U
bind -r C-l select-pane -R

# moving between windows with vim next and previous keys
bind -r C-p select-window -t :-
bind -r C-n select-window -t :+

# resize panes with vim movement keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Config reload
bind R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."
