setw -g mode-keys vi

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

set -sg escape-time 1

# Base indices
set -g base-index 1
setw -g pane-base-index 1

# mouse behavior
set -g mouse on

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on
