set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'jaclu/tmux-menus'

# Check for tpm in different location. Run if available, prioritizing the globally installed version.
if-shell '[ -x /usr/share/tmux-plugin-manager/tpm/tpm ]' \
  "run '/usr/share/tmux-plugin-manager/tpm/tpm'" \
  "if-shell '[ -x ~/.config/tmux/plugins/tpm/tpm ]' \
    'run ~/.config/tmux/plugins/tpm/tpm'"
