set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'jaclu/tmux-menus'

# Check for tpm in different location. Run if available, prioritizing the globally installed version.
run-shell 'if [ -x /usr/share/tmux-plugin-manager/tpm ]; then
  exec /usr/share/tmux-plugin-manager/tpm
elif [ -x "$HOME/.config/tmux/plugins/tpm/tpm" ]; then
  exec "$HOME/.config/tmux/plugins/tpm/tpm"
fi'
