require 'modules.default_apps'
require 'modules.globals'
require 'modules.environment_variables'
require 'modules.permissions'
require 'modules.autostart'
require 'modules.app_themes'
require 'modules.binds.init'
require 'modules.input'
require 'modules.look_and_feel'
require 'modules.misc'
require 'modules.monitors'
require 'modules.windows_and_workspaces'
hl.config { debug = { disable_logs = false } }
