[general]
import = [
        "~/.config/alacritty/keybindings.toml",
        "~/.config/alacritty/fonts.toml",
        "~/.config/alacritty/opacity.toml",
        "~/.config/alacritty/cyberdream.toml",
]
